repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, '.:src', --py37-plus]
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      args: [--config, setup.cfg]
      additional_dependencies:
        - flake8-docstrings
        - flake8-annotations-complexity
        - flake8-expression-complexity
        - flake8-literal
        - flake8-multiline-containers
        - flake8-print
        - flake8-logging-format
        - flake8-builtins
        - flake8-cognitive-complexity
        - flake8-comprehensions
        - flake8-datetime-import
        - flake8-warnings
        - flake8_implicit_str_concat
        - flake8-SQL
        - flake8-simplify
        - flake8-scream
        - flake8-fixme
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      args: ['-c', 'pyproject.toml']
      additional_dependencies: ['bandit[toml]']
