version: "3.9"

services:
  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - database-data:/var/mongo/data

  cache:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - cache-data:/var/redis/data

  api:
#    build: .
    image: ssi91/ton_metrix_api:local
    ports:
      - '8000:8000'
    depends_on:
      - database
      - cache

volumes:
  database-data:
  cache-data:
